name: Build And Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          format: table
          severity: HIGH,CRITICAL
          exit-code: "0"

      - name: Build Docker image
        run: |
          docker build -t 599626781401.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest .

      - name: Trivy image scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 599626781401.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: "0"

      - name: Push image to ECR
        run: echo "push"